package views;

import controllers.AdoptionController;
import models.NonEditableTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

public class AllAdoptions extends javax.swing.JFrame {

    /**
     * Creates new form AllAdoprtions
     */
    public AllAdoptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        previousAdoptionLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        adoptionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Previous Adoptions");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(255, 255, 204));

        previousAdoptionLabel.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        previousAdoptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previousAdoptionLabel.setText("Previous Adoptions");

        backButton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        adoptionTable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        adoptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adoption ID", "Volunteer Name", "Volunteer ID", "Pet Name", "Pet ID", "Adopted Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adoptionTable);
        if (adoptionTable.getColumnModel().getColumnCount() > 0) {
            adoptionTable.getColumnModel().getColumn(0).setResizable(false);
            adoptionTable.getColumnModel().getColumn(1).setResizable(false);
            adoptionTable.getColumnModel().getColumn(2).setResizable(false);
            adoptionTable.getColumnModel().getColumn(3).setResizable(false);
            adoptionTable.getColumnModel().getColumn(4).setResizable(false);
            adoptionTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(previousAdoptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previousAdoptionLabel))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Goto Adotions Frame
        AdoptionFrame adoptionFrame = new AdoptionFrame();
        adoptionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Refresh the table from the database
        try {
            AdoptionController controller = new AdoptionController();
            ResultSet results = controller.getAdoptionData();
            
            NonEditableTableModel tableModel = new NonEditableTableModel(new Object[0][6], new String[]{"Adoption ID", "Volunteer Name", "Volunteer ID", "Pet Name", "Pet ID", "Adopted Date"});

            while (results.next()) {
                int adoptionId = Integer.parseInt(results.getString("adoption_id"));
                String volunteerName = results.getString("volunteer");
                int volunteerId = Integer.parseInt(results.getString("volunteer_id"));
                String petName = results.getString("pet");                
                int petId = Integer.parseInt(results.getString("pet_id"));
                String adoptedDate = results.getString("adopted_date");

                tableModel.addRow(new Object[]{adoptionId, volunteerName, volunteerId, petName, petId, adoptedDate});
            }
            
            adoptionTable.setModel(tableModel);
            
            if (adoptionTable.getColumnModel().getColumnCount() > 0) {
                adoptionTable.getColumnModel().getColumn(0).setResizable(false);
                adoptionTable.getColumnModel().getColumn(1).setResizable(false);
                adoptionTable.getColumnModel().getColumn(2).setResizable(false);
                adoptionTable.getColumnModel().getColumn(3).setResizable(false);
                adoptionTable.getColumnModel().getColumn(4).setResizable(false);
                adoptionTable.getColumnModel().getColumn(5).setResizable(false);
            }
        }
        catch (NumberFormatException | SQLException e){
            System.out.println("ERROR - SQL Error loading data");
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllAdoptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllAdoptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllAdoptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllAdoptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllAdoptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable adoptionTable;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel previousAdoptionLabel;
    // End of variables declaration//GEN-END:variables
}
